workflows:
    ios-detox:
        name: iOS Detox Tests
        environment:
            node: v18
            xcode: latest
            cocoapods: default
            vars:
                # Disable Yarn’s immutable install mode that is automatically enabled when CI=true
                # This avoids the “YN0028: The lockfile would have been modified by this install” error
                YARN_ENABLE_IMMUTABLE_INSTALLS: "false"
            groups:
              - codepush-group
        triggering:
            events:
                - push
            branch_patterns:
                - pattern: main
                  include: true
                  source: true
        scripts:
            - name: Install Codemagic CodePush CLI tools
              script: |
                  npm install -g @codemagic/code-push-cli
            - name: CodePush authentication
              script: |
                  echo "CODEPUSH_TOKEN: $CODEPUSH_TOKEN"
                  code-push login "https://codepush.pro" --key $CODEPUSH_TOKEN
            - name: CodePush add app # this script can be skipped if you have existing apps
              script: |
                  code-push app add CodeMagicSample
                  code-push app ls
            - name: Install npm dependencies
              script: |
                npm install
            - name: Codepush deployment
              script: |
                  code-push deployment ls CodeMagicSample -k
                  code-push release-react CodeMagicSample ios -d Staging# -d refers to the deployment name e.g. Production, Staging
                  code-push release-react CodeMagicSample android -d Staging # -d refers to the deployment name e.g. Production, Staging
            - name: Install Yarn dependencies
              script: |
                yarn install
            - name: Install Detox dependencies (applesimutils)
              script: |
                brew tap wix/brew && brew install applesimutils
            - name: Install detox-cli globally
              script: |
                npm install -g detox-cli
            - name: Install CocoaPods dependencies
              script: |
                cd ios && pod install --repo-update
            - name: List available simulator device types
              script: |
                xcrun simctl list devicetypes | cat
            - name: List available simulators (applesimutils)
              script: |
                # Lists all simulators currently available along with their UDIDs and states
                applesimutils --list | cat
            - name: Create iPhone 14 simulator if it does not exist
              script: |
                DEVICE_NAME="iPhone 14"
                DEVICE_TYPE="com.apple.CoreSimulator.SimDeviceType.iPhone-14"

                # Get the latest available iOS runtime (ignoring unavailable ones)
                IOS_RUNTIME=$(xcrun simctl list runtimes | grep -E "^iOS" | grep -v unavailable | tail -n 1 | awk '{print $NF}' | tr -d '()')

                # Create the simulator only if it doesn't already exist
                if ! xcrun simctl list devices | grep -q "$DEVICE_NAME ("; then
                  echo "Creating simulator $DEVICE_NAME with runtime $IOS_RUNTIME"
                  xcrun simctl create "$DEVICE_NAME" "$DEVICE_TYPE" "$IOS_RUNTIME"
                else
                  echo "Simulator $DEVICE_NAME already exists"
                fi
            - name: Boot the simulator
              script: |
                xcrun simctl boot "iPhone 14"
            - name: Build the app for Detox (Debug simulator)
              script: |
                detox build -c ios.sim.debug -l verbose
            - name: Start Metro server
              script: |
                # Start Metro in the background so it stays alive for the following Detox tests
                yarn start --port 8081 --reset-cache &
            - name: Run Detox tests (Debug simulator)
              script: |
                detox test -c ios.sim.debug -l verbose --cleanup
        artifacts:            
            - ios/build/Build/**/*.app
            - ~/Library/Detox/Artifacts/**
    android-build:
        name: Android Build
        environment:
            node: v18          
            java: 17           
            vars:
                # Disable Yarn’s immutable install mode that is automatically enabled when CI=true
                # This avoids the “YN0028: The lockfile would have been modified by this install” error
                YARN_ENABLE_IMMUTABLE_INSTALLS: "false"
        triggering:
            events:
                - push
            branch_patterns:
                - pattern: main
                  include: true
                  source: true
        scripts:
            - name: Install Yarn dependencies
              script: |
                yarn install
            - name: Set Android SDK location
              script: |
                echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
            - name: Build Android release (APK)
              script: |
                cd android
                ./gradlew assembleRelease --stacktrace --warning-mode all
        artifacts:
            - android/app/build/outputs/**/*.apk