workflows:
    ios-detox:
        name: iOS Detox Tests
        environment:
            node: v18
            xcode: latest # Pin to a version (e.g. 15.0) if you want to avoid sudden updates
            cocoapods: default
        triggering:
            events:
                - push
            branch_patterns:
                - pattern: main
                  include: true
                  source: true
        scripts:
            - name: Install Yarn dependencies
              script: |
                yarn install --frozen-lockfile --non-interactive
            - name: Install Detox dependencies (applesimutils)
              script: |
                brew tap wix/brew && brew install applesimutils
            - name: Install detox-cli globally
              script: |
                npm install -g detox-cli
            - name: Install CocoaPods dependencies
              script: |
                cd ios && pod install --repo-update
            - name: List available simulator device types
              script: |
                xcrun simctl list devicetypes | cat
            - name: List available simulators (applesimutils)
              script: |
                # Lists all simulators currently available along with their UDIDs and states
                applesimutils --list | cat
            - name: Create iPhone 14 simulator if it does not exist
              script: |
                DEVICE_NAME="iPhone 14"
                DEVICE_TYPE="com.apple.CoreSimulator.SimDeviceType.iPhone-14"

                # Get the latest available iOS runtime (ignoring unavailable ones)
                IOS_RUNTIME=$(xcrun simctl list runtimes | grep -E "^iOS" | grep -v unavailable | tail -n 1 | awk '{print $NF}' | tr -d '()')

                # Create the simulator only if it doesn't already exist
                if ! xcrun simctl list devices | grep -q "$DEVICE_NAME ("; then
                  echo "Creating simulator $DEVICE_NAME with runtime $IOS_RUNTIME"
                  xcrun simctl create "$DEVICE_NAME" "$DEVICE_TYPE" "$IOS_RUNTIME"
                else
                  echo "Simulator $DEVICE_NAME already exists"
                fi
            - name: Boot the simulator
              script: |
                xcrun simctl boot "iPhone 14"
            - name: Build the app for Detox (Debug simulator)
              script: |
                detox build -c ios.sim.debug -l verbose
            - name: Run Detox tests (Debug simulator)
              script: |
                detox test -c ios.sim.debug -l verbose --cleanup
        artifacts:
            # Store the built .app bundle and detox log artefacts for debugging, this is optional
            - ios/build/Build/**/*.app
            - ~/Library/Detox/Artifacts/**